version: "3"

services:
  chatservice:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
    environment:
      - CASSANDRA_HOST=cassandra
      - REDIS_HOST=redis
    networks:
      - chatnet

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - chatnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
